name: Playwright Tests

on:
  push:
    branches:
      - '**'
    paths-ignore:
      - README.md
      - playwright.yml

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright/python:v1.53.0-noble

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: 17

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Playwright Tests
      run: pytest -v --alluredir=allure-results || true

    - name: Load test report history
      uses: actions/checkout@v3
      if: always()
      continue-on-error: true
      with:
        path: build/allure-results

    - name: Build test report
      uses: simple-elf/allure-report-action@v1.7
      if: always()
      with:
        allure_history: allure-history
        allure_results: build/allure-results

    - name: Upload Playwright Traces
      if: ${{ !cancelled() }}
      uses: actions/upload-artifact@v4
      with:
        name: playwright-traces
        path: trace/
        retention-days: 7

