name: Playwright Tests

on:
  push:
    branches:
      - '**'
    paths-ignore:
      - README.md
      - playwright.yml

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright/python:v1.53.0-noble

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Allure CLI
      run: |
        apt-get update && apt-get install -y wget tar openjdk-11-jre
        wget https://github.com/allure-framework/allure2/releases/download/2.27.0/allure-2.27.0.tgz
        tar -zxvf allure-2.27.0.tgz
        echo "$PWD/allure-2.27.0/bin" >> $GITHUB_PATH

    - name: Run Playwright Tests
      run: pytest -v --alluredir=allure-results || true

    - name: Generate Allure Report
      run: allure generate allure-results --clean -o allure-report

    - name: Upload Allure Report as artifact
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: allure-report
        path: allure-report

    - name: Upload Playwright Traces
      if: ${{ !cancelled() }}
      uses: actions/upload-artifact@v4
      with:
        name: playwright-traces
        path: trace/
        retention-days: 7

